spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/appbarber
spring.datasource.username=fulupao123
spring.datasource.password=${SENHA_DO_BANCO}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true