spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/appbarber?serverTimezone=America/Sao_Paulo
spring.datasource.username=fulupao123
spring.datasource.password=${DATABASE_PASSWORD}

spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${SECRET_JWT}